name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  root-tests:
    permissions:
      contents: read
    concurrency:
      group: ${{ github.workflow }}:${{ github.ref }}:root-tests
      cancel-in-progress: true
    uses: matt-riley/matt-riley-ci/.github/workflows/ci.yml@cb986078a5bd4775e5fb05348f3618e41fedf4de # v4
    with:
      install: true
      working-directory: .
      lint: false
      test: true
      build: false

  web-build:
    permissions:
      contents: read
    concurrency:
      group: ${{ github.workflow }}:${{ github.ref }}:web-build
      cancel-in-progress: true
    uses: matt-riley/matt-riley-ci/.github/workflows/ci.yml@cb986078a5bd4775e5fb05348f3618e41fedf4de # v4
    with:
      install: true
      working-directory: clients/web
      lint: false
      test: false
      build: true
