name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  root-tests:
    uses: matt-riley/matt-riley-ci/.github/workflows/ci.yml@2aa90cd79663d10959d67faf89a3ecce29392f6a # v2
    with:
      install: true
      working-directory: .
      lint: false
      test: true
      build: false
      concurrency-suffix: root-tests

  web-build:
    uses: matt-riley/matt-riley-ci/.github/workflows/ci.yml@2aa90cd79663d10959d67faf89a3ecce29392f6a # v2
    with:
      install: true
      working-directory: clients/web
      lint: false
      test: false
      build: true
      concurrency-suffix: web-build
